// exporting the 'types' object, with corresponding property
export default {
  VIEW_CHANGED: 'VIEW_CHANGED',
  TEST_LIST_REQUESTED: 'TEST_LIST_REQUESTED',
  PRODUCT_LIST_REQUESTED: 'PRODUCT_LIST_REQUESTED',
  PRODUCT_DETAILS_REQUESTED: 'PRODUCT_DETAILS_REQUESTED',
  PRODUCT_ADDED_TO_CART: 'PRODUCT_ADDED_TO_CART',
  CART_SORTED: 'CART_SORTED',
  SET_CURRENT_PRODUCT: 'SET_CURRENT_PRODUCT',
  CART_TOTAL_COMPUTED: 'CART_TOTAL_COMPUTED'
}
