// exporting the 'types' object, with corresponding property
export default {
  VIEW_CHANGED: 'VIEW_CHANGED',
  TEST_LIST_REQUESTED: 'TEST_LIST_REQUESTED',
  PRODUCT_LIST_REQUESTED: 'PRODUCT_LIST_REQUESTED',
  PRODUCT_DETAILS_REQUESTED: 'PRODUCT_DETAILS_REQUESTED',
  PRODUCT_ADDED_TO_CART: 'PRODUCT_ADDED_TO_CART',
  PRODUCT_REMOVED_FROM_CART: 'PRODUCT_REMOVED_FROM_CART',
  CART_SORTED: 'CART_SORTED',
  INCREASED_PRODUCT_QUANTITY: 'INCREASED_PRODUCT_QUANTITY',
  REDUCED_PRODUCT_QUANTITY: 'REDUCED_PRODUCT_QUANTITY',
  SET_CURRENT_PRODUCT: 'SET_CURRENT_PRODUCT',
  CART_TOTAL_COMPUTED: 'CART_TOTAL_COMPUTED',
  CHECKOUT_FORM_SUBMITTED: 'CHECKOUT_FORM_SUBMITTED',
  PREVIOUS_Y_SAVED: 'PREVIOUS_Y_SAVED'
}
